/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { ErrorDetails1 } from '../models/errorDetails1.js';
import { ErrorLinkDescription } from '../models/errorLinkDescription.js';

/**
 * Creates an instance of ErrorError1
 */
interface ErrorError1 {
  /** The human-readable, unique name of the error. */
  name: string;
  /** The message that describes the error. */
  message: string;
  /** The PayPal internal ID. Used for correlation purposes. */
  debug_id: string;
  /** An array of additional details about the error. */
  details?: ErrorDetails1[];
  /** An array of request-related [HATEOAS links](/api/rest/responses/#hateoas-links). */
  links?: ErrorLinkDescription[];
}

export class ErrorError1Error extends ApiError<ErrorError1> {}
