/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import { ErrorDetails1, errorDetails1Schema } from './errorDetails1.js';
import {
  ErrorLinkDescription,
  errorLinkDescriptionSchema,
} from './errorLinkDescription.js';

/** The error details. */
export interface Error1 {
  /** The human-readable, unique name of the error. */
  name: string;
  /** The message that describes the error. */
  message: string;
  /** The PayPal internal ID. Used for correlation purposes. */
  debugId: string;
  /** An array of additional details about the error. */
  details?: ErrorDetails1[];
  /** An array of request-related [HATEOAS links](/api/rest/responses/#hateoas-links). */
  links?: ErrorLinkDescription[];
}

export const error1Schema: Schema<Error1> = lazy(() =>
  object({
    name: ['name', string()],
    message: ['message', string()],
    debugId: ['debug_id', string()],
    details: ['details', optional(array(errorDetails1Schema))],
    links: ['links', optional(array(errorLinkDescriptionSchema))],
  })
);
