/**
 * PayPal Server SDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';
import { LinkHttpMethod, linkHttpMethodSchema } from './linkHttpMethod.js';

/** The error-related [HATEOAS link](/api/rest/responses/#hateoas-links) information. Identical to `link_description` except that `rel` is optional: the live API omits `rel` on the documentation link it returns with `RESOURCE_NOT_FOUND` errors, so a client that requires it cannot read the error at all. */
export interface ErrorLinkDescription {
  /** The complete target URL. To make the related call, combine the method with this [URI Template-formatted](https://tools.ietf.org/html/rfc6570) link. For pre-processing, include the `$`, `(`, and `)` characters. The `href` is the key HATEOAS component that links a completed call with a subsequent call. */
  href: string;
  /** The [link relation type](https://tools.ietf.org/html/rfc5988#section-4), which serves as an ID for a link that unambiguously describes the semantics of the link. See [Link Relations](https://www.iana.org/assignments/link-relations/link-relations.xhtml). */
  rel?: string;
  /** The HTTP method required to make the related call. */
  method?: LinkHttpMethod;
}

export const errorLinkDescriptionSchema: Schema<ErrorLinkDescription> = object({
  href: ['href', string()],
  rel: ['rel', optional(string())],
  method: ['method', optional(linkHttpMethodSchema)],
});
